# Generated by Django 4.0.6 on 2022-08-29 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carrera_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='programa',
            options={'ordering': ['nombre']},
        ),
        migrations.AlterModelOptions(
            name='universidad',
            options={'ordering': ['universidad']},
        ),
    ]
