# Generated by Django 4.0.6 on 2022-09-19 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carrera_app', '0003_alter_universidad_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='programa',
            options={'ordering': ['nombre'], 'verbose_name': 'Programa Académico', 'verbose_name_plural': 'Programas Académicos'},
        ),
    ]
