# Generated by Django 4.0.6 on 2022-07-24 23:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('proyectos_app', '0002_proyecto_tutores'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsignacionEvaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('evaluadores', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('proyecto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='proyectos_app.proyecto')),
            ],
        ),
    ]
