# Generated by Django 4.0.6 on 2022-09-19 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asignacion_evaluador', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asignacionevaluacion',
            options={'verbose_name': 'Asignación de Valorador', 'verbose_name_plural': 'Asignaciones de valoradores'},
        ),
    ]
