# Generated by Django 4.0.6 on 2022-07-25 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asignacion_evaluador', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignacionevaluacion',
            name='asignacion_calificada1',
            field=models.BooleanField(default=False),
        ),
    ]
