# Generated by Django 4.0.6 on 2022-07-25 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asignacion_evaluador', '0002_asignacionevaluacion_asignacion_calificada1'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignacionevaluacion',
            name='asignacion_calificada2',
            field=models.BooleanField(default=False),
        ),
    ]
