# Generated by Django 4.0.6 on 2022-09-19 16:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('proyectos_app', '0009_alter_proyecto_options_and_more'),
        ('asignacion_evaluador', '0002_alter_asignacionevaluacion_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asignacionevaluacion',
            options={'verbose_name': 'Asignación de Valorador semilleros', 'verbose_name_plural': 'Asignaciones de valoradores semilleros'},
        ),
        migrations.CreateModel(
            name='AsignacionEvaluacionInngeniatec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('evaluadores', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('proyecto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='proyectos_app.proyectoinngeniatec')),
            ],
            options={
                'verbose_name': 'Asignación de Valorador inngeniatec',
                'verbose_name_plural': 'Asignaciones de inngeniatec',
            },
        ),
    ]
