# Generated by Django 4.0.6 on 2022-09-19 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asignacion_evaluador', '0003_alter_asignacionevaluacion_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asignacionevaluacioninngeniatec',
            options={'verbose_name': 'Asignación de Valorador inngeniatec', 'verbose_name_plural': 'Asignaciones de valoradores inngeniatec'},
        ),
    ]
