# Generated by Django 4.0.6 on 2022-10-05 08:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('asignacion_evaluador', '0005_asignacionevaluacioninngeniatec_asignacion_calificada1'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoriaCambiosAsignacionSemilleros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observaciones', models.CharField(blank=True, max_length=10000, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('Asignacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asignacion_evaluador.asignacionevaluacion')),
                ('valoracdores_anteriores', models.ManyToManyField(related_name='valoradores_anteriores', to=settings.AUTH_USER_MODEL)),
                ('valoradores_nuevos', models.ManyToManyField(related_name='valoradores_nuevos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historia de cambios en la asignación de valoradores de Semilleros',
                'verbose_name_plural': 'Historias de cambios en la asignación de valoradores de Semilleros',
            },
        ),
    ]
