# Generated by Django 4.0.6 on 2022-10-05 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asignacion_evaluador', '0006_historiacambiosasignacionsemilleros'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historiacambiosasignacionsemilleros',
            old_name='Asignacion',
            new_name='asignacion',
        ),
    ]
