# Generated by Django 4.0.6 on 2022-11-15 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config_semilleros_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configpaginasemilleros',
            name='parrafo_secundario1',
            field=models.TextField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='configpaginasemilleros',
            name='parrafo_secundario2',
            field=models.TextField(max_length=10000),
        ),
    ]
