branch-defaults:
  main:
    environment: semillerosadminsys-env
    group_suffix: null
global:
  application_name: semillerosadminsys
  branch: null
  default_ec2_keyname: '1'
  default_platform: Python 3.7
  default_region: us-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
