# Generated by Django 4.0.6 on 2022-08-02 07:57

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('proyectos_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('evaluaciones_preseleccion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivacionCalificacionOral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=1000)),
                ('activacion_calificacion_oral', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='EvaluacionOral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dominio_tematico', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)])),
                ('expresion_oral', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)])),
                ('creatividad_diseño', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)])),
                ('observaciones', models.CharField(blank=True, max_length=1500)),
                ('is_calificado', models.BooleanField(default=False)),
                ('fecha_evaluacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('evaluador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('proyecto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='proyectos_app.proyecto')),
            ],
        ),
        migrations.CreateModel(
            name='CalificacionFinalProyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_calificacion', models.DateTimeField(auto_now_add=True)),
                ('evaluacion_oral', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='evaluaciones_orales.evaluacionoral')),
                ('evaluacion_preseleccion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='evaluaciones_preseleccion.evaluacionpreseleccion')),
            ],
        ),
    ]
