# Generated by Django 4.0.6 on 2022-07-19 23:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('proyectos_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluacionOral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dominio_tematico', models.FloatField()),
                ('expresion_oral', models.FloatField()),
                ('creatividad_diseño', models.FloatField()),
                ('observaciones', models.CharField(blank=True, max_length=1500)),
                ('is_calificado', models.BooleanField(default=False)),
                ('fecha_evaluacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('evaluador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('proyecto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='proyectos_app.proyecto')),
            ],
        ),
    ]
