# Generated by Django 4.0.6 on 2022-09-19 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones_orales', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='evaluacionoral',
            options={'verbose_name': 'Valoración Oral', 'verbose_name_plural': 'Valoraciones orales'},
        ),
    ]
