# Generated by Django 4.0.6 on 2022-07-20 00:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones_orales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluacionoral',
            name='creatividad_diseño',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)]),
        ),
        migrations.AlterField(
            model_name='evaluacionoral',
            name='dominio_tematico',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)]),
        ),
        migrations.AlterField(
            model_name='evaluacionoral',
            name='expresion_oral',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)]),
        ),
    ]
