# Generated by Django 4.0.6 on 2022-07-20 00:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones_preseleccion', '0001_initial'),
        ('evaluaciones_orales', '0002_alter_evaluacionoral_creatividad_diseño_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalificacionFinalProyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_calificacion', models.DateTimeField(auto_now_add=True)),
                ('evaluacion_oral', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='evaluaciones_orales.evaluacionoral')),
                ('evaluacion_preseleccion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='evaluaciones_preseleccion.evaluacionpreseleccion')),
            ],
        ),
    ]
