# Generated by Django 4.0.6 on 2022-07-26 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones_orales', '0003_calificacionfinalproyecto'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivacionCalificacionOral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=1000)),
                ('activacion_calificacion_oral', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
