# Generated by Django 4.0.6 on 2022-09-19 16:12

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos_app', '0009_alter_proyecto_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('evaluaciones_preseleccion', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='evaluacionpreseleccion',
            options={'verbose_name': 'Valoración de preselección', 'verbose_name_plural': 'valoraciones de preselección'},
        ),
        migrations.CreateModel(
            name='ValoracionProyectoIngeniatec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aplicacion_escenario_real', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)])),
                ('originadidad_innovacion', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)])),
                ('calidad_tecnica', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)])),
                ('estudio_viablididad', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)])),
                ('fecha_evaluacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('evaluador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('proyecto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='proyectos_app.proyecto')),
            ],
            options={
                'verbose_name': 'Valoración Inngeniatec',
                'verbose_name_plural': 'valoraciones Inngeniatec',
            },
        ),
    ]
