# Generated by Django 4.0.6 on 2022-09-19 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos_app', '0009_alter_proyecto_options_and_more'),
        ('evaluaciones_preseleccion', '0002_alter_evaluacionpreseleccion_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='valoracionproyectoingeniatec',
            name='proyecto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='proyectos_app.proyectoinngeniatec'),
        ),
    ]
