# Generated by Django 4.0.6 on 2022-09-19 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones_preseleccion', '0003_alter_valoracionproyectoingeniatec_proyecto'),
    ]

    operations = [
        migrations.AddField(
            model_name='valoracionproyectoingeniatec',
            name='is_calificado',
            field=models.BooleanField(default=False),
        ),
    ]
