# Generated by Django 4.0.6 on 2022-09-22 15:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones_preseleccion', '0004_valoracionproyectoingeniatec_is_calificado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='valoracionproyectoingeniatec',
            name='estudio_viablididad',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)]),
        ),
    ]
