# Generated by Django 4.0.6 on 2022-10-05 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones_preseleccion', '0005_alter_valoracionproyectoingeniatec_estudio_viablididad'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivacionCalificacionPreseleccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=1000)),
                ('activacion_calificacion_preseleccion', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
