# Generated by Django 4.0.6 on 2022-10-05 09:42

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('proyectos_app', '0010_alter_proyecto_options_and_more'),
        ('evaluaciones_preseleccion', '0006_activacioncalificacionpreseleccion'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValoracionProyectoIngeniatecPresencial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aplicacion_escenario_real', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)])),
                ('originadidad_innovacion', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)])),
                ('calidad_tecnica', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)])),
                ('estudio_viablididad', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)])),
                ('is_calificado', models.BooleanField(default=False)),
                ('fecha_evaluacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('evaluador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('proyecto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='proyectos_app.proyectoinngeniatec')),
            ],
            options={
                'verbose_name': 'Valoración Inngeniatec evento en vivo',
                'verbose_name_plural': 'valoraciones Inngeniatec evento en vivo',
            },
        ),
    ]
