# Generated by Django 4.0.6 on 2022-10-05 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones_preseleccion', '0007_valoracionproyectoingeniatecpresencial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivacionCalificacionInngeniatecPrimeraFase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=1000)),
                ('activacion_calificacion_inngeriatec1', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ActivacionCalificacionInngeniatecSegundaFase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=1000)),
                ('activacion_calificacion_inngeriatec1', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
