# Generated by Django 4.0.6 on 2022-08-02 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('carrera_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('nombres', models.CharField(max_length=1000)),
                ('apellidos', models.CharField(max_length=1000)),
                ('correo_institicional', models.EmailField(max_length=1000, unique=True)),
                ('username', models.CharField(max_length=1000, unique=True)),
                ('no_documento', models.IntegerField(blank=True, default=0)),
                ('id_iniversidad', models.CharField(max_length=1000)),
                ('is_autor', models.BooleanField(default=False)),
                ('is_evaluador', models.BooleanField(default=False)),
                ('is_tutor', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(auto_now=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('is_superadmin', models.BooleanField(default=False)),
                ('programa_academico', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='carrera', to='carrera_app.programa')),
                ('universidad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='universidad2', to='carrera_app.universidad')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
