# Generated by Django 4.0.6 on 2022-08-01 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carrera_app', '0003_remove_programa_universidad'),
        ('usuarios_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='universidad',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='universidad2', to='carrera_app.universidad'),
        ),
    ]
