# Generated by Django 4.0.6 on 2022-09-09 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('semillero_app', '0003_alter_semillero_grupo_investigació'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='semillero',
            options={'ordering': ('nombre',)},
        ),
    ]
