# Generated by Django 4.0.6 on 2022-07-19 23:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tematica_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('semillero_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=1000)),
                ('modalidad_aprticipacion', models.CharField(max_length=1000)),
                ('url_video', models.URLField(max_length=1000)),
                ('proyecto_pdf', models.FileField(upload_to='files/proyectos')),
                ('carta_aval_pdf', models.FileField(upload_to='files/cartas_Aval')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('autores', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('semillero', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='semillero_app.semillero')),
                ('tematica', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tematica_app.tematica')),
            ],
        ),
    ]
