# Generated by Django 4.0.6 on 2022-09-02 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='carta_aval_pdf',
            field=models.FileField(max_length=1000, upload_to='files/cartas_Aval'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='proyecto_pdf',
            field=models.FileField(max_length=1000, upload_to='files/proyectos'),
        ),
    ]
