# Generated by Django 4.0.6 on 2022-07-22 20:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('proyectos_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='tutores',
            field=models.ManyToManyField(related_name='tutores', to=settings.AUTH_USER_MODEL),
        ),
    ]
