# Generated by Django 4.0.6 on 2022-09-19 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos_app', '0003_activacionconvocatoria_alter_proyecto_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProyectoInngeniatec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=1000)),
                ('integrantes', models.CharField(max_length=1000)),
                ('programa_integrantes', models.CharField(max_length=1000)),
                ('tutor', models.CharField(max_length=1000)),
                ('palabras_clave', models.CharField(max_length=1000)),
                ('resumen', models.CharField(max_length=100000)),
                ('url_video', models.URLField(blank=True, default=None, max_length=1000, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-fecha_creacion',),
            },
        ),
    ]
