# Generated by Django 4.0.6 on 2022-09-19 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos_app', '0005_proyectoinngeniatec_email_contacto'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyectoinngeniatec',
            name='categoria',
            field=models.CharField(default=None, max_length=1000),
        ),
    ]
