# Generated by Django 4.0.6 on 2022-09-19 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos_app', '0006_proyectoinngeniatec_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyectoinngeniatec',
            name='email_contacto',
            field=models.CharField(blank=True, default=None, max_length=1000, null=True),
        ),
    ]
