# Generated by Django 4.0.6 on 2022-09-19 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos_app', '0007_alter_proyectoinngeniatec_email_contacto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyectoinngeniatec',
            name='integrantes',
            field=models.CharField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='proyectoinngeniatec',
            name='palabras_clave',
            field=models.CharField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='proyectoinngeniatec',
            name='titulo',
            field=models.CharField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='proyectoinngeniatec',
            name='url_video',
            field=models.URLField(blank=True, default=None, max_length=10000, null=True),
        ),
    ]
