# Generated by Django 4.0.6 on 2022-09-22 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos_app', '0009_alter_proyecto_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proyecto',
            options={'ordering': ('titulo',), 'verbose_name': 'Proyecto de semillero', 'verbose_name_plural': 'Proyectos de Semilleros'},
        ),
        migrations.AlterModelOptions(
            name='proyectoinngeniatec',
            options={'ordering': ('titulo',), 'verbose_name': 'Proyecto de Inngeniatec', 'verbose_name_plural': 'Proyectos de Inngeniatec'},
        ),
    ]
