# Generated by Django 4.0.6 on 2022-11-16 16:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('proyectos_app', '0011_proyecto_es_finalista_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proyectoinngeniatec',
            name='tutor',
        ),
        migrations.AddField(
            model_name='proyectoinngeniatec',
            name='tutores',
            field=models.ManyToManyField(related_name='tutoresInn', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='proyectoinngeniatec',
            name='categoria',
            field=models.CharField(choices=[('Clase básico (de 1er a 5to semestre)', 'Clase básico (de 1er a 5to semestre)'), ('Proyecto colegiados', 'Proyecto colegiados'), ('Clase avanzado (de 6to a 10vo semestre)', 'Clase avanzado (de 6to a 10vo semestre)'), ('Proyecto de grado', 'Proyecto de grado'), ('Emprendimiento', 'Emprendimiento')], default='Clase básico (de 1er a 5to semestre)', max_length=250),
        ),
        migrations.RemoveField(
            model_name='proyectoinngeniatec',
            name='integrantes',
        ),
        migrations.AddField(
            model_name='proyectoinngeniatec',
            name='integrantes',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
