# Generated by Django 4.0.6 on 2022-11-16 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos_app', '0012_remove_proyectoinngeniatec_tutor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyectoinngeniatec',
            name='resumen',
            field=models.TextField(max_length=100000),
        ),
    ]
