# Generated by Django 4.0.6 on 2022-11-16 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos_app', '0013_alter_proyectoinngeniatec_resumen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.IntegerField(default=2023)),
                ('semestre', models.CharField(choices=[('Primer semestre', 'Primer semestre'), ('Segundo semestre', 'Segundo semestre')], default='Primer semestre', max_length=250)),
            ],
        ),
        migrations.AddField(
            model_name='proyectoinngeniatec',
            name='periodo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='proyectos_app.periodo'),
        ),
    ]
