# Generated by Django 4.0.6 on 2022-11-16 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos_app', '0014_periodo_proyectoinngeniatec_periodo'),
    ]

    operations = [
        migrations.AddField(
            model_name='periodo',
            name='slug',
            field=models.CharField(default='sin-periodo-definido', max_length=100),
        ),
    ]
