# Generated by Django 4.0.6 on 2022-11-16 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos_app', '0015_periodo_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='periodo',
            name='slug',
            field=models.CharField(max_length=100),
        ),
    ]
