# Generated by Django 4.0.6 on 2022-11-16 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos_app', '0016_alter_periodo_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='periodo',
            name='slug',
        ),
    ]
