# Generated by Django 4.0.6 on 2022-11-16 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos_app', '0019_periodo_proyectoinngeniatec_periodo'),
    ]

    operations = [
        migrations.AddField(
            model_name='periodo',
            name='slug',
            field=models.CharField(default='Sin definir', max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
