# Generated by Django 4.0.6 on 2022-11-16 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos_app', '0020_periodo_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='periodo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='proyectos_app.periodo'),
        ),
    ]
