# Generated by Django 4.0.6 on 2022-12-09 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos_app', '0022_activacionconvocatoriainngeniatec'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyectoinngeniatec',
            name='documento',
            field=models.FileField(max_length=1000, null=True, upload_to='files/proyectosInngeniatec'),
        ),
    ]
